### PR TITLE
travis: update go version

### PR DESCRIPTION
**Pull request by dvrkps**
.x match latest stable subversion.

### CODE REVIEW

**Comment by dvrkps** [comment]
@benlaurie ping :) happy holidays.

**Comment by dvrkps** [comment]
@benlaurie ping :)

**Comment by benlaurie** [comment]
Hey, sorry I missed this, is it still the right thing to do?

**Comment by dvrkps** [comment]
@benlaurie, yes. or wait month or two and move to 1.10.x :)

**Pull request closed without merging**
